int shell_cd(char **args, char ***envp);
int shell_exit(char **args, char ***envp, char **d_or, char **d_ampersand, char **semicolon);
int shell_env(char **args, char ***envp);
int shell_setenv(char **args, char ***envp);
int shell_unsetenv(char **args, char ***envp);
int shell_alias(char **args, char ***alias);
void handle_comments(char **args);
int shell_execute(char **args, char ***envp, char **d_or, char **d_ampersand, char **semicolon, int status);
int strings_compare(const char *s1, const char *s2);
int convert_string_to_int(char *source_string);
void print_line(char *line);
int call_execve(char *name, char **args, char **envp, char **d_or, char **d_ampersand, char **semicolon, int i);
int shell_fork_and_run(char **args, char **envp, char **d_or, char **d_ampersand, char **semicolon);
char *get_index(char *source, char character);
char **copy_envp(char *envp[]);
char **add_envp(char *envp[], char *add_new);
char **remove_envp(char *envp[], char *remove_ptr);
int write_to_str(char *source, char *dest, char term);
int write_to_index(char *source, char *dest, char term, char index);
char *search_dir(char **args, char **envp);
char *get_env(char *name, char **envp);
int get_env_index(char *name, char **envp);
int string_ncompare(const char *s, const char *t, int n);
char *dir_path(char *s1, char *s2);
int string_length(char *str);
int print_char(char c);
void print_tab(char **split);
void free_tab(char **split);
char *read_line(const int fd);
char **string_split(const char *str, char separator);
char **v_names(char *args);
char *replace_variable_names(char *args, char **names, char **envp);
void check_convert_dollar_question(char **args, int status);
void convert_error_int_to_string(int number, char *a);